### ISSUE TITLE
Preprocessed data sets not available

### ISSUE THREAD

**Issue by larissamumme** [ActiveVisionLab/NINormal#1]
When opening the sharepoint links there is an error message.

**Comment by ziruiw-dev** [comment]
Sorry, we stored our data and models on our University's OneDrive account. The access policy was changed few weeks ago. We will fix the link shortly.

**Comment by larissamumme** [comment]
That would be great as I would like to use the algorithm in my bachelor thesis. Thank you!

**Comment by ziruiw-dev** [comment]
Hi @larissamumme,

Sorry for the delay. Could you please send your email address to ryan[AT]robots.ox.ac.uk. I have not found a good way to share it through a public link but I can share it to your email address as a quick fix for now.

Best,
Zirui
